-- ============================================================================
-- Migración 6: cobertura nacional. Las 16 regiones y sus 346 comunas.
-- Orden norte → sur en regions.sort_order. La RM y sus 52 comunas ya existían.
-- ============================================================================
alter table public.regions add column if not exists sort_order smallint not null default 0;

insert into public.regions (id, name, active) values
  (15, 'Región de Arica y Parinacota', true),
  (1, 'Región de Tarapacá', true),
  (2, 'Región de Antofagasta', true),
  (3, 'Región de Atacama', true),
  (4, 'Región de Coquimbo', true),
  (5, 'Región de Valparaíso', true),
  (6, 'Región del Libertador General Bernardo O''Higgins', true),
  (7, 'Región del Maule', true),
  (16, 'Región de Ñuble', true),
  (8, 'Región del Biobío', true),
  (9, 'Región de La Araucanía', true),
  (14, 'Región de Los Ríos', true),
  (10, 'Región de Los Lagos', true),
  (11, 'Región de Aysén del General Carlos Ibáñez del Campo', true),
  (12, 'Región de Magallanes y de la Antártica Chilena', true)
on conflict (id) do nothing;

update public.regions set active = true;
update public.regions set sort_order = v.ord from (values (15,1), (1,2), (2,3), (3,4), (4,5), (5,6), (13,7), (6,8), (7,9), (16,10), (8,11), (9,12), (14,13), (10,14), (11,15), (12,16)) as v(id, ord) where regions.id = v.id;

insert into public.comunas (region_id, name) values
  (15, 'Arica'),
  (15, 'Camarones'),
  (15, 'Putre'),
  (15, 'General Lagos'),
  (1, 'Iquique'),
  (1, 'Alto Hospicio'),
  (1, 'Pozo Almonte'),
  (1, 'Camiña'),
  (1, 'Colchane'),
  (1, 'Huara'),
  (1, 'Pica'),
  (2, 'Antofagasta'),
  (2, 'Mejillones'),
  (2, 'Sierra Gorda'),
  (2, 'Taltal'),
  (2, 'Calama'),
  (2, 'Ollagüe'),
  (2, 'San Pedro de Atacama'),
  (2, 'Tocopilla'),
  (2, 'María Elena'),
  (3, 'Copiapó'),
  (3, 'Caldera'),
  (3, 'Tierra Amarilla'),
  (3, 'Chañaral'),
  (3, 'Diego de Almagro'),
  (3, 'Vallenar'),
  (3, 'Alto del Carmen'),
  (3, 'Freirina'),
  (3, 'Huasco'),
  (4, 'La Serena'),
  (4, 'Coquimbo'),
  (4, 'Andacollo'),
  (4, 'La Higuera'),
  (4, 'Paiguano'),
  (4, 'Vicuña'),
  (4, 'Illapel'),
  (4, 'Canela'),
  (4, 'Los Vilos'),
  (4, 'Salamanca'),
  (4, 'Ovalle'),
  (4, 'Combarbalá'),
  (4, 'Monte Patria'),
  (4, 'Punitaqui'),
  (4, 'Río Hurtado'),
  (5, 'Valparaíso'),
  (5, 'Casablanca'),
  (5, 'Concón'),
  (5, 'Juan Fernández'),
  (5, 'Puchuncaví'),
  (5, 'Quintero'),
  (5, 'Viña del Mar'),
  (5, 'Isla de Pascua'),
  (5, 'Los Andes'),
  (5, 'Calle Larga'),
  (5, 'Rinconada'),
  (5, 'San Esteban'),
  (5, 'La Ligua'),
  (5, 'Cabildo'),
  (5, 'Papudo'),
  (5, 'Petorca'),
  (5, 'Zapallar'),
  (5, 'Quillota'),
  (5, 'La Calera'),
  (5, 'Hijuelas'),
  (5, 'La Cruz'),
  (5, 'Nogales'),
  (5, 'San Antonio'),
  (5, 'Algarrobo'),
  (5, 'Cartagena'),
  (5, 'El Quisco'),
  (5, 'El Tabo'),
  (5, 'Santo Domingo'),
  (5, 'San Felipe'),
  (5, 'Catemu'),
  (5, 'Llaillay'),
  (5, 'Panquehue'),
  (5, 'Putaendo'),
  (5, 'Santa María'),
  (5, 'Quilpué'),
  (5, 'Limache'),
  (5, 'Olmué'),
  (5, 'Villa Alemana'),
  (6, 'Rancagua'),
  (6, 'Codegua'),
  (6, 'Coinco'),
  (6, 'Coltauco'),
  (6, 'Doñihue'),
  (6, 'Graneros'),
  (6, 'Las Cabras'),
  (6, 'Machalí'),
  (6, 'Malloa'),
  (6, 'Mostazal'),
  (6, 'Olivar'),
  (6, 'Peumo'),
  (6, 'Pichidegua'),
  (6, 'Quinta de Tilcoco'),
  (6, 'Rengo'),
  (6, 'Requínoa'),
  (6, 'San Vicente'),
  (6, 'Pichilemu'),
  (6, 'La Estrella'),
  (6, 'Litueche'),
  (6, 'Marchigüe'),
  (6, 'Navidad'),
  (6, 'Paredones'),
  (6, 'San Fernando'),
  (6, 'Chépica'),
  (6, 'Chimbarongo'),
  (6, 'Lolol'),
  (6, 'Nancagua'),
  (6, 'Palmilla'),
  (6, 'Peralillo'),
  (6, 'Placilla'),
  (6, 'Pumanque'),
  (6, 'Santa Cruz'),
  (7, 'Talca'),
  (7, 'Constitución'),
  (7, 'Curepto'),
  (7, 'Empedrado'),
  (7, 'Maule'),
  (7, 'Pelarco'),
  (7, 'Pencahue'),
  (7, 'Río Claro'),
  (7, 'San Clemente'),
  (7, 'San Rafael'),
  (7, 'Cauquenes'),
  (7, 'Chanco'),
  (7, 'Pelluhue'),
  (7, 'Curicó'),
  (7, 'Hualañé'),
  (7, 'Licantén'),
  (7, 'Molina'),
  (7, 'Rauco'),
  (7, 'Romeral'),
  (7, 'Sagrada Familia'),
  (7, 'Teno'),
  (7, 'Vichuquén'),
  (7, 'Linares'),
  (7, 'Colbún'),
  (7, 'Longaví'),
  (7, 'Parral'),
  (7, 'Retiro'),
  (7, 'San Javier'),
  (7, 'Villa Alegre'),
  (7, 'Yerbas Buenas'),
  (16, 'Chillán'),
  (16, 'Bulnes'),
  (16, 'Chillán Viejo'),
  (16, 'El Carmen'),
  (16, 'Pemuco'),
  (16, 'Pinto'),
  (16, 'Quillón'),
  (16, 'San Ignacio'),
  (16, 'Yungay'),
  (16, 'Quirihue'),
  (16, 'Cobquecura'),
  (16, 'Coelemu'),
  (16, 'Ninhue'),
  (16, 'Portezuelo'),
  (16, 'Ránquil'),
  (16, 'Treguaco'),
  (16, 'San Carlos'),
  (16, 'Coihueco'),
  (16, 'Ñiquén'),
  (16, 'San Fabián'),
  (16, 'San Nicolás'),
  (8, 'Concepción'),
  (8, 'Coronel'),
  (8, 'Chiguayante'),
  (8, 'Florida'),
  (8, 'Hualqui'),
  (8, 'Lota'),
  (8, 'Penco'),
  (8, 'San Pedro de la Paz'),
  (8, 'Santa Juana'),
  (8, 'Talcahuano'),
  (8, 'Tomé'),
  (8, 'Hualpén'),
  (8, 'Lebu'),
  (8, 'Arauco'),
  (8, 'Cañete'),
  (8, 'Contulmo'),
  (8, 'Curanilahue'),
  (8, 'Los Álamos'),
  (8, 'Tirúa'),
  (8, 'Los Ángeles'),
  (8, 'Antuco'),
  (8, 'Cabrero'),
  (8, 'Laja'),
  (8, 'Mulchén'),
  (8, 'Nacimiento'),
  (8, 'Negrete'),
  (8, 'Quilaco'),
  (8, 'Quilleco'),
  (8, 'San Rosendo'),
  (8, 'Santa Bárbara'),
  (8, 'Tucapel'),
  (8, 'Yumbel'),
  (8, 'Alto Biobío'),
  (9, 'Temuco'),
  (9, 'Carahue'),
  (9, 'Cunco'),
  (9, 'Curarrehue'),
  (9, 'Freire'),
  (9, 'Galvarino'),
  (9, 'Gorbea'),
  (9, 'Lautaro'),
  (9, 'Loncoche'),
  (9, 'Melipeuco'),
  (9, 'Nueva Imperial'),
  (9, 'Padre Las Casas'),
  (9, 'Perquenco'),
  (9, 'Pitrufquén'),
  (9, 'Pucón'),
  (9, 'Saavedra'),
  (9, 'Teodoro Schmidt'),
  (9, 'Toltén'),
  (9, 'Vilcún'),
  (9, 'Villarrica'),
  (9, 'Cholchol'),
  (9, 'Angol'),
  (9, 'Collipulli'),
  (9, 'Curacautín'),
  (9, 'Ercilla'),
  (9, 'Lonquimay'),
  (9, 'Los Sauces'),
  (9, 'Lumaco'),
  (9, 'Purén'),
  (9, 'Renaico'),
  (9, 'Traiguén'),
  (9, 'Victoria'),
  (14, 'Valdivia'),
  (14, 'Corral'),
  (14, 'Lanco'),
  (14, 'Los Lagos'),
  (14, 'Máfil'),
  (14, 'Mariquina'),
  (14, 'Paillaco'),
  (14, 'Panguipulli'),
  (14, 'La Unión'),
  (14, 'Futrono'),
  (14, 'Lago Ranco'),
  (14, 'Río Bueno'),
  (10, 'Puerto Montt'),
  (10, 'Calbuco'),
  (10, 'Cochamó'),
  (10, 'Fresia'),
  (10, 'Frutillar'),
  (10, 'Los Muermos'),
  (10, 'Llanquihue'),
  (10, 'Maullín'),
  (10, 'Puerto Varas'),
  (10, 'Castro'),
  (10, 'Ancud'),
  (10, 'Chonchi'),
  (10, 'Curaco de Vélez'),
  (10, 'Dalcahue'),
  (10, 'Puqueldón'),
  (10, 'Queilén'),
  (10, 'Quellón'),
  (10, 'Quemchi'),
  (10, 'Quinchao'),
  (10, 'Osorno'),
  (10, 'Puerto Octay'),
  (10, 'Purranque'),
  (10, 'Puyehue'),
  (10, 'Río Negro'),
  (10, 'San Juan de la Costa'),
  (10, 'San Pablo'),
  (10, 'Chaitén'),
  (10, 'Futaleufú'),
  (10, 'Hualaihué'),
  (10, 'Palena'),
  (11, 'Coyhaique'),
  (11, 'Lago Verde'),
  (11, 'Aysén'),
  (11, 'Cisnes'),
  (11, 'Guaitecas'),
  (11, 'Cochrane'),
  (11, 'O''Higgins'),
  (11, 'Tortel'),
  (11, 'Chile Chico'),
  (11, 'Río Ibáñez'),
  (12, 'Punta Arenas'),
  (12, 'Laguna Blanca'),
  (12, 'Río Verde'),
  (12, 'San Gregorio'),
  (12, 'Cabo de Hornos'),
  (12, 'Antártica'),
  (12, 'Porvenir'),
  (12, 'Primavera'),
  (12, 'Timaukel'),
  (12, 'Natales'),
  (12, 'Torres del Paine')
on conflict (region_id, name) do nothing;

create index if not exists comunas_name_idx on public.comunas(name);
